### ISSUE TITLE
Question about notify_connect and notify_disconnect

### ISSUE THREAD

**Issue by zhjunqin** [Licenser/mdns_client_lib#1]
Hi,

I have a question about notify_connect and notify_disconnect.
I just found that mdns_client_lib_connection_event:notify_connect(Service) was called when server was added.
But mdns_client_lib_connection_event:notify_disconnect was never called even server was removed.
So my question is it is a bug or not?
Is it done on purpose? Any background?
Thanks.

**Comment by Licenser** [comment]
notify_disconnect should be called when the _last_ server is rmoved

**Comment by zhjunqin** [comment]
I see. Thanks for reply.
